---
name: 'deploy'

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Cloning repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Push to TejPage
        uses: dokku/github-action@master
        with:
          git_remote_url: 'ssh://test-troy-2@tejpage.com:22/gitact'
          ssh_private_key: ${{ secrets.DEPLOY_KEY }}
